version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    command: ./docker-entrypoint.sh

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: